language: ruby
rvm:
- 2.7.0
addons:
  ssh_known_hosts: sdongzhi.com
before_install:
- openssl aes-256-cbc -K $encrypted_8e6aadf5448b_key -iv $encrypted_8e6aadf5448b_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host sdongzhi.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- bundle install
- bundle exec jekyll build
after_success:
- git clone https://github.com/IORI20091101/darknights.me.git
- cd darknights.me && rm -rf * && cp -r ../_site/* .
- git config user.name "IORI20091101"
- git config user.email "sundongzhi11014111@126.com"
- git add --all .
- git commit -m "Travis CI Auto Builder"
- git push --force https://$JEKYLL_GITHUB_TOKEN@github.com/IORI20091101/darknights.me.git
  master
- ssh root@sdongzhi.com "docker restart darknights"
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
